version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:11
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: Compile Java Code
          command: javac -d target src/**/*.java

  test_ERP:
    docker:
      - image: openjdk:11
    steps:
      - checkout
      - run:
          name: Run Java Tests ERP
          command: java -cp target org.junit.runner.JUnitCore Revendeurs/src/test/java/com/example/Revendeurs/RevendeursApplicationTests.java

  test_CRM:
    docker:
      - image: openjdk:11
    steps:
      - checkout
      - run:
          name: Run Java Tests CRM
          command: java -cp target org.junit.runner.JUnitCore WebShop/src/test/java/com/example/WebShop/WebShopApplicationTests.java

  deploy:
    docker:
      - image: openjdk:11
    steps:
      - checkout
      - run:
          name: Deploy to Server
          command: |
            ssh user@your_server_ip "mkdir -p src"
            scp -r ./* user@your_server_ip:/src

workflows:
  version: 2.1
  mspr2ERP:
    jobs:
      - build
      - test_ERP:
          requires:
            - build 
      - test_CRM:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test_ERP
            - test_CRM
          filters:
            branches:
              only: main 
